hotels/urls.py
from django.urls import path, include
from . import views


urlpatterns = [
    path('', views.show_hotels, name = 'show_hotels'),
]

unique_hotels/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('hotels.urls')),
    path('', include('users.urls')),
    path('user/', include('user_profile.urls')),
    path('', include('contact_forms.urls'))
] 

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views


urlpatterns = [
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.UserSignUp.as_view(), name='signup'),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='password/password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name="password/password_reset_confirm.html"), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='password/password_reset_complete.html'), name='password_reset_complete'),
    path("password-reset", views.password_reset_request, name="password_reset")
]

hotels/models.py
# from django.db import models
from django.contrib.auth.models import User
from django.contrib.gis.db import models


# Create your models here.
class Country(models.Model):
    name = models.CharField(max_length=100, unique=True)

    def __str__(self):
        return self.name

class Location(models.Model):
    city = models.CharField(max_length=100)
    country = models.ForeignKey(Country, on_delete=models.CASCADE)

    class Meta:
        unique_together = ('city', 'country')

    def __str__(self):
        return self.city + ', ' + self.country.name

class Hotels(models.Model):
    name = models.CharField(max_length=100)
    location = models.ForeignKey(Location, on_delete=models.SET_NULL, null=True)
    point_coordinates = models.PointField()
    unique_snippet = models.CharField(max_length=500)
    details = models.CharField(max_length=2000)
    liked_by_user = models.ManyToManyField(User, related_name='liked')
    rejected_by_user = models.ManyToManyField(User, related_name='rejected')
    booking_website = models.URLField()
    approved = models.BooleanField(default=True)
    contact_email = models.EmailField(null=True)

    def __str__(self):
        return self.name

    class Meta:
        unique_together = ('name', 'location')
   
class HotelPhotos(models.Model):
    image = models.ImageField()
    hotel = models.ForeignKey(Hotels, on_delete=models.CASCADE)    

    def __str__(self):
        return self.hotel.name

class Coordinates(models.Model):
    hotel = models.OneToOneField(Hotels, on_delete=models.CASCADE)
    lat = models.DecimalField(max_digits=10, decimal_places=7)
    lon = models.DecimalField(max_digits=10, decimal_places=7)

class Categories(models.Model):
    name = models.CharField(max_length=100)
    hotel = models.ManyToManyField(Hotels, blank=True)
    
    def __str__(self):
        return self.name

class Amenities(models.Model):
    name = models.CharField(max_length=100)
    hotel = models.ManyToManyField(Hotels, blank=True)

    def __str__(self):
        return self.name

hotels/forms.py
from django import forms
from .models import Categories, Amenities

class CategoryForm(forms.Form):
    category_options = Categories.objects.all().values_list('pk', 'name')
    categories = forms.MultipleChoiceField(
        required=False,
        widget=forms.CheckboxSelectMultiple,
        choices=category_options
    )

class AmenityForm(forms.Form):
    amenity_options = Amenities.objects.all().values_list('pk', 'name')
    amenities = forms.MultipleChoiceField(
        required=False,
        widget=forms.CheckboxSelectMultiple,
        choices=amenity_options
    )

class LocationForm(forms.Form):
    lat = forms.FloatField(required=False)
    lon = forms.FloatField(required=False)
    radius = forms.IntegerField(required=False)

    def __init__(self, *args, **kwargs):
        super(LocationForm, self).__init__(*args, **kwargs)
        self.fields['radius'].label = "Kilometers"

hotels/views.py
from django.shortcuts import render, redirect
from .models import Hotels, HotelPhotos
from random import choice
from django.contrib.auth.decorators import login_required
from users import models
from .forms import CategoryForm, AmenityForm, LocationForm
from django.contrib.gis.geos import GEOSGeometry
from django.contrib.gis.measure import D

# Create your views here.
def filter_hotels(hotels, *args):
    filtered_hotels = hotels #needs to be assigned in order for the forloop assignment to be able to be passed back
    for category in args[0]:
        filtered_hotels = filtered_hotels.filter(categories=category) 

    for amenity in args[1]:
        filtered_hotels = filtered_hotels.filter(amenities=amenity) 

    if args[2] and args[3] and args[4]:
        location = GEOSGeometry(f'POINT({args[3]} {args[2]})')#points are long/lat and get location is lat/long, so it has to be reversed
        filtered_hotels = filtered_hotels.filter(point_coordinates__distance_lte=(location, D(km=(args[4]))))
        print(type(args[4]))

    if len(filtered_hotels) == 0: 
            return False

    return filtered_hotels


def choose_hotel(current_user, *args):
    if current_user.is_authenticated:
        unjudged_hotels = Hotels.objects.exclude(liked_by_user=current_user).exclude(
            rejected_by_user=current_user).exclude(approved=False)
        if len(unjudged_hotels) == 0:  # if the user has judged all the hotels on the site
            return False
    else:
        unjudged_hotels = Hotels.objects.exclude(approved=False)

    filtered_hotels = filter_hotels(unjudged_hotels, *args)
    if filtered_hotels == False: 
            return False
        
    return choice(filtered_hotels)


def show_hotels(request):
    current_user = request.user
    if request.method == 'POST':
        if current_user.is_authenticated:
            hotel = Hotels.objects.get(pk=request.POST.get('hotel_pk'))
            if 'like' in request.POST:
                current_user.liked.add(hotel)
            if 'reject' in request.POST:
                current_user.rejected.add(hotel)

        elif 'skip' not in request.POST:  # user should be able to skip through hotels even if not logged in
            return redirect('login')
    
    locationForm = LocationForm(request.GET)
    if locationForm.is_valid():#the only form that takes a user input so it needs to be cleaned
        if 'lat' in request.GET and 'radius' in request.GET:
            lat = locationForm.cleaned_data['lat']
            lon = locationForm.cleaned_data['lon']
            distance = locationForm.cleaned_data['radius']
        else:
            lat, lon, distance = None, None, None
    chosen_hotel = choose_hotel(current_user, request.GET.getlist('categories'), request.GET.getlist('amenities'), lat, lon, distance)
    
    context = {
        'hotel': chosen_hotel,
        'cat_form': CategoryForm(request.GET),
        'amen_form': AmenityForm(request.GET),
        'dist_form': LocationForm(request.GET)
    }

    if chosen_hotel == False:
        return render(request, 'hotels/nohotels.html', context)

    return render(request, 'hotels/showhotels.html', context)

hotels/templates/partials/hotel_filters.html
<form method="GET" class="py-3 navbar navbar-expand-lg navbar-light">
    <button class="navbar-toggler pull-left" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span>Filter by</span>
    </button>
    <div class="collapse navbar-collapse filter-toggle" id="navbarNavDropdown">
        <span class='filters filter-label'>Filter by:</span>
        <div class="dropdown filters navbar-nav">
            <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Categories
            </button>
            <div class="dropdown-menu">
                    {{ cat_form }}
            </div>
        </div>
        <div class="dropdown filters navbar-nav">
            <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Amenities
            </button>
            <div class="dropdown-menu">
                    {{ amen_form }}
            </div>
        </div>
        <div class="dropdown filters navbar-nav">
            <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" onclick='getLocation()'>
                Distance
            </button>
            <div class="dropdown-menu">
                {{ dist_form.radius.label}}:
                {{ dist_form.lat.as_hidden }}
                {{ dist_form.lon.as_hidden }}
                {{ dist_form.radius }}
            </div>
        </div>
        <button type="submit" class="btn btn-primary filters filter-submit navbar-nav">Submit</button>
    </div>
</form>

hotels/templates/partials/hotelcards.html
<div class="card hotel-card" id='hotel-card' draggable="true">
    <h5 class="card-header">{{ hotel.name }}</h5>
    <div id="carouselControls-{{ forloop.counter }}" class="carousel slide card-img-top" data-ride="carousel">
        <div class="carousel-inner">
            {% for photo in hotel.hotelphotos_set.all %}
                {% if photo == hotel.hotelphotos_set.all.0 %}
                    <div class="carousel-item active">
                {% else %}
                    <div class="carousel-item">
                {% endif %}
                        <img src="{{ photo.image.url }}" class="d-block w-100 img-responsive hotel-img" alt="{{ hotel.name }}">
                    </div>
            {% endfor %}
        </div>
        <a class="carousel-control-prev" href="#carouselControls-{{ forloop.counter }}" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselControls-{{ forloop.counter }}" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
        </a>
    </div>
    <div class="card-body text-center hotel-unique-desc">
        <p class="card-text">{{ hotel.unique_snippet }}</p>
    </div>
    {% if current_page != 'profile' %}
    <div class="card-body text-center">
        <form method='POST'>
            {% csrf_token %}
            <input type='hidden' name='hotel_pk' value='{{ hotel.pk }}'>
            <button type='submit' name='reject' class='reject-button choice float-left' id='reject'><i class="fas fa-times"></i></button>
        </form>
        <form method='POST' class='skip-form'>
            {% csrf_token %}
            <input type='hidden' name='hotel_pk' value='{{ hotel.pk }}'>
            <button type='submit' name='skip' class='skip-button choice'><i class="fas fa-forward"></i></button>
        </form>
        <form method='POST' class='float-right'>
            {% csrf_token %}
            <input type='hidden' name='hotel_pk' value='{{ hotel.pk }}'>
            <button type='submit' name='like' class='like-button choice'><i class="far fa-heart" id='like_heart'></i></button>
        </form>
    </div>
    <!-- check if logged in as self when viewing the profile page -->
    {% elif self %}
        <form method='POST' class='text-center like_unlike'>
            {% csrf_token %}
            <input type='hidden' name='hotel_pk' value='{{ hotel.pk }}'>
            <button type='submit' name='like' class='like-button choice red'><i class="fas fa-heart"></i></button>
        </form>
    {% endif %}

    <div class="card-footer">
        <a class="btn btn-primary" data-toggle="collapse" href="#moreDetails-{{ forloop.counter }}" role="button"
            aria-expanded="false">More Details</a>
        <a href="{{ hotel.booking_website }}" target='_blank' class="btn btn-secondary float-right">Check Availability and Rates</a>
    </div>

    <div class="collapse" id="moreDetails-{{ forloop.counter }}">
        <div class="card card-body">
            <h3>About {{ hotel.name }}:</h3>
            <p>{{ hotel.details }}</p>
            {% if hotels.amenities_set.all != '[]' %}
            <h3>Amenities:</h3>
            <ul>
                {% for amenity in hotel.amenities_set.all %}
                <li>{{ amenity }}</li>
                {% endfor %}
            </ul>
            {% endif %}
            {% if hotels.categories_set.all != '[]' %}
            <h3>Categories:</h3>
            <ul>
                {% for category in hotel.categories_set.all %}
                <li>{{ category }}</li>
                {% endfor %}
            </ul>
            {% endif %}
        </div>
    </div>
</div>